# Using ollama and postgres for the vector, doc and index store. Ollama is also used for embeddings.
# To use install these extras:
# poetry install --extras "llms-ollama ui vector-stores-postgres embeddings-ollama storage-nodestore-postgres"
server:
  env_name: ${APP_ENV:ollama}

llm:
  mode: ollama
  max_new_tokens: 512
  context_window: 3900

embedding:
  mode: ollama
  embed_dim: 1024

ollama:
  llm_model: TheBlokeMistral7BInstructv02
  embedding_model: bge-large-en-v1.5
  api_base: http://localhost:11434

nodestore:
  database: postgres

vectorstore:
  database: postgres

postgres:
  host: ${PG_DATABASE_IP_VARIABLE}
  port: ${PG_DATABASE_PORT_VARIABLE}
  database: ${PG_DATABASE_VARIABLE}
  user: ${PG_USER_VARIABLE}
  password: ${PG_PASSWORD_VARIABLE}
  schema_name: ${PG_SCHEMA_VARIABLE}

