# poetry install --extras "ui llms-llama-cpp vector-stores-postgres storage-nodestore-postgres embeddings-huggingface llms-openai-like"
# poetry run python scripts/setup
# $Env:PGPT_PROFILES="local"
server:
  env_name: ${APP_ENV:local}

llm:
  mode: llamacpp
  # Should be matching the selected model
  max_new_tokens: 512
  context_window: 3900
  tokenizer: lmstudio-ai/gemma-2b-it-GGUF

llamacpp:
  prompt_style: "default"
  llm_hf_repo_id: lmstudio-ai/gemma-2b-it-GGUF
  llm_hf_model_file: gemma-2b-it-q4_k_m.gguf

embedding:
  mode: huggingface
  ingest_mode: batch
  count_workers: 2
  embed_dim: 1024

huggingface:
  embedding_hf_model_name: mixedbread-ai/mxbai-embed-large-v1

vectorstore:
  database: postgres

postgres:
  host: ${PG_DATABASE_IP_VARIABLE}
  port: ${PG_DATABASE_PORT_VARIABLE}
  database: ${PG_DATABASE_VARIABLE}
  user: ${PG_USER_VARIABLE}
  password: ${PG_PASSWORD_VARIABLE}
  schema_name: ${PG_SCHEMA_VARIABLE}